
import gimnasio.AlmacenGimnasio;
import gimnasio.AlmacenRegistro;
import gimnasio.Registro;
import gimnasio.Socio;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sergio
 */
public class jfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jbCarga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAreaSocios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jbCarga.setText("Carga Socios");
        jbCarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCargaMouseClicked(evt);
            }
        });
        jbCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargaActionPerformed(evt);
            }
        });
        getContentPane().add(jbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jtAreaSocios.setColumns(20);
        jtAreaSocios.setRows(5);
        jScrollPane1.setViewportView(jtAreaSocios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 520, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCargaMouseClicked
        // TODO add your handling code here:
        
       AlmacenGimnasio al=new AlmacenGimnasio("C:\\ClasesBasicoII\\Gimnasio\\Ficheros");
       al.carga();
       
       jtAreaSocios.setText(al.toString());
    }//GEN-LAST:event_jbCargaMouseClicked

    private void jbCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbCarga;
    private javax.swing.JTextArea jtAreaSocios;
    // End of variables declaration//GEN-END:variables
}
